

INCLUDE
SWFN.INC /
INCLUDE
SOF2.INC /

PVTW
-- FIELD UNITS:
-- Pref    Bw         cw         mu_w(Pref)      Cv_w(viscosibility)
3501.51	   1.00	  1.000000e-26	   0.30		      0.00	 /
-- UNITS: cP (METRIC), cP (FIELD), cP (LAB), cP (PVT-M)

PVCDO
-- FIELD UNITS:
--  1)          2)            3)           4)
 5801.00	1.00	  1.000000e-32	   0.50	 /
-- Column 1:  Oil phase pressure
-- Column 2:  Oil FVF
-- Column 3:  Oil Compressibility
-- Column 4:  Oil Viscosity

ROCK
--   Pref	cr
   5801.0   1.00E-032	 /

DENSITY
--  1)      2)      3)
  53.10	  62.40	 0.0440	 /
-- Column 1:  Oil density at surface cond. lb/ft3
-- Column 2:  Water density at surface cond. lb/ft3
-- Column 3:  Gas density at surface cond. lb/ft3