
WELSPECS
  I01 INJECTOR  19  43  1*  WATER 2* SHUT YES/
  I02 INJECTOR  28  32  1*  WATER 2* SHUT YES/
  I03 INJECTOR  42  20  1*  WATER 2* SHUT YES/
  I04 INJECTOR  55  28  1*  WATER 2* SHUT YES/
  I05 INJECTOR  67  19  1*  WATER 2* SHUT YES/
  I06 INJECTOR  72  29  1*  WATER 2* SHUT YES/
  I07 INJECTOR  99  23  1*  WATER 2* SHUT YES/
  I08 INJECTOR  93  27  1*  WATER 2* SHUT YES/
  I09 INJECTOR 105  32  1*  WATER 2* SHUT YES/
  I10 INJECTOR 114  41  1*  WATER 2* SHUT YES/
  P01 PRODUCER  65  43  1*  OIL   2* SHUT YES/
  P02 PRODUCER  56  41  1*  OIL   2* SHUT YES/  
/

COMPDAT
  I01  19  43  3 9 OPEN 1*  2.0  0.219 3* Z /
  I02  28  32  1 9 OPEN 1*  2.0  0.219 3* Z /
  I03  42  20  1 9 OPEN 1*  2.0  0.219 3* Z /
  I04  55  28  1 9 OPEN 1*  2.0  0.219 3* Z /
  I05  67  19  1 9 OPEN 1*  2.0  0.219 3* Z /
  I06  72  29  1 9 OPEN 1*  2.0  0.219 3* Z /
  I07  99  23  1 9 OPEN 1*  2.0  0.219 3* Z /
  I08  93  27  1 9 OPEN 1*  2.0  0.219 3* Z /
  I09 105  32  1 9 OPEN 1*  2.0  0.219 3* Z /
  I10 114  41  1 9 OPEN 1*  2.0  0.219 3* Z /
  P01  65  43  3 3 OPEN 1*  2.0  0.219 3* Z /
  P01  66  43  4 4 OPEN 1*  2.0  0.219 3* Z /
  P02  56  41  3 3 OPEN 1*  2.0  0.219 3* Z /
  P02  57  41  4 4 OPEN 1*  2.0  0.219 3* Z /  
/

WCONINJE
  I01       WATER  OPEN  BHP   2*   170  /
  I02       WATER  OPEN  BHP   2*   170  /
  I03       WATER  OPEN  BHP   2*   170  /
  I04       WATER  OPEN  BHP   2*   170  /
  I05       WATER  OPEN  BHP   2*   170  /
  I06       WATER  OPEN  BHP   2*   170  /
  I07       WATER  OPEN  BHP   2*   170  /
  I08       WATER  OPEN  BHP   2*   170  /
  I09       WATER  OPEN  BHP   2*   170  /
  I10       WATER  OPEN  BHP   2*   170  /
/

WCONPROD
  P01       OPEN  BHP   5*   70 /
  P02       OPEN  BHP   5*   70 /  
/

TSTEP
  1*2 /
TSTEP
  100*100 /

--TSTEP
--1*2 /
--
--TSTEP
--5*73 /
--
---- 2
--TSTEP
--5*73 /
--
---- 3
--TSTEP
--5*73 /
--
---- 4
--TSTEP
--5*73 /
--
---- 5
--TSTEP
--5*73 /
--
---- 6
--TSTEP
--5*73 /
--
---- 7
--TSTEP
--5*73 /
--
---- 8
--TSTEP
--5*73 /
--
---- 9
--TSTEP
--5*73 /
--
---- 10
--TSTEP
--5*73 /
