#ifndef GSSOPTIMIZER_GLOBAL_H
#define GSSOPTIMIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GSSOPTIMIZER_LIBRARY)
#  define GSSOPTIMIZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GSSOPTIMIZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GSSOPTIMIZER_GLOBAL_H
