WELSPECS
-- 1)   2)   3)   4)   5)     6)
   PROD1   G2    2   2    1700   OIL /
/

-- 1) Well name
-- 2) Name of group to which well belongs
-- 3) I-location of well head or heel (x)
-- 4) J-location of well head or heel (y)
-- 5) Reference depth for bottom hole pressure
-- 6) Preferred phase for the well

-- ____________________________________________________
COMPDAT
-- 1)  2)  3) 4) 5)  6)    7)  8)  9)      10-13) 14)
PROD1  2   2  1  3   OPEN  1   1*  0.1905  4*     1*  /
/


-- ____________________________________________________
WCONPROD
-- 1)  2)    3)   4)  5)  6)  7)  8)  9)
 PROD1  OPEN  BHP  1*  1*  1*  1*  1*  90  /
/


