BootStrap: docker
From: einar90/fieldopt:develop

# Build using
#   singularity build ~/Singularity-Containers/fieldopt-develop.img ~/git/PCG/FieldOpt/Docker/Develop/Singularity
#

# These need to be changed to fit the paths you want to use.
# The paths must exist in the environment on which you want
# to launch the container.
%post
    mkdir -p /work/einarjba/fieldopt/singularity

%post
    # Setup a very minimal bashrc file
    mkdir -p /opt
    echo 'PS1="Singularity \w> "' > /opt/bashrc

%runscript
    echo "@ Welcome to the Singularity FieldOpt container"

    # Disable annoying sudo message
    touch ~/.sudo_as_admin_successful

    exec /bin/bash --rcfile /opt/bashrc "$@"
